### ISSUE TITLE
sorting the file names

### ISSUE THREAD

**Issue by hobbyman** [bernardop/vscode-working-sets#1]
This extension is an **awesome** idea. Thanks!

Feature Request:
Would love to be able to sort the file names within a working set.
Either by drag-n-drop or alphabetically.

**Comment by bernardop** [comment]
Thank you, @hobbyman!
This is one of the things I thought about adding, but didn't make the cut for the initial release. I'll add it for sure in the near future 👍. I'll keep this issue open and update it once it's done.

**Comment by joshuaiz** [comment]
+1 for this feature.

**Comment by bernardop** [comment]
I'm working on this, should have a new version out there some time tomorrow.
