### ISSUE TITLE
"Add all open editors" only adds some files

### ISSUE THREAD

**Issue by svArtist** [bernardop/vscode-working-sets#14]
I can't figure out by what criteria it's adding the tabs.
After some trying out, it's never added all of them.
It doesn't appear to be linked to which tabs were recently active, either.
https://user-images.githubusercontent.com/13470026/111060584-3ee7a600-849e-11eb-9629-e37140070c01.mp4

Also, clicking it changes the active tab, which is quite undesirable :(

Working Sets: v1.3.1

VS Code:
Version: 1.54.2 (user setup)
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:19.848Z (3 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by bernardop** [comment]
This is a [known issue](https://github.com/bernardop/vscode-working-sets#known-issues), the way this extension handles the saving of open editors is a bit of a "hack". There's [an issue in the vscode repo](https://github.com/microsoft/vscode/issues/15178) (that's been open for years) for providing a better API for this. Until that gets addressed, we're kind of stuck with this spotty behavior.
