### ISSUE TITLE
Move working sets to another project

### ISSUE THREAD

**Issue by reefhound** [bernardop/vscode-working-sets#19]
I had an extensive collection of working sets for a project. For the next release they created a new project and repo. Exact same file structure. Is it possible to move the working sets to the new project, either through the extension UI or copy/modify extension data files?

**Comment by reefhound** [comment]
Beuhler? Anyone? I was able to copy/move the working sets by copying the sqlite extensions data files in workingstorage but it sure would be nice if we could import/export working sets to json. It's basically just a list of filenames so shouldn't be hard.

**Comment by bernardop** [comment]
Sorry for the (big) delay on this! I just published `v1.4.0` where you should be able to do this with the `saveWorkingSetsInWorkspace` setting.

**Comment by reefhound** [comment]
Thanks, this is a big step forward. To import into another project do I just copy the working_sets.json file? 

One enhancement, would be to have a baseUrl property like that in tsconfig.json and then store filenames in the project as relative paths. This would make it much easier to move and share working sets since my repo may not be in the same system path as my co-workers. But I do understand vscode can open files anywhere in the filesystem so those outside the project would need absolute paths. 

But if this is too much complication then I can fairly easily do a search/replace of parent path in the settings file, thanks to this update.
